### PR TITLE
fix: temporary fix cannot import vite in Yarn PnP

### LINKED ISSUE #15: v1.0.0 fails in Yarn projects with Plug'n'Play
Following [this commit](https://github.com/KusStar/vite-bundle-visualizer/commit/c334fc9f1ee573a25d1bbcad7b75b61dba1fba6f), Yarn projects with [Plug'n'Play](https://yarnpkg.com/features/pnp) no longer works (version `0.11.0` worked so long as the project set ` yarn unplug vite-bundle-visualizer`).

The error after upgrading to 1.0.0:

```
❯ yarn vite-bundle-visualizer
file:///...project.../.yarn/cache/import-from-esm-npm-1.3.3-4c64f297d5-4287ff7e7b.zip/node_modules/import-from-esm/index.js:100
		const error = new Error(errorString);
		              ^

Error: Cannot find module 'vite'
    at importFrom (file:///...project.../.yarn/cache/import-from-esm-npm-1.3.3-4c64f297d5-4287ff7e7b.zip/node_modules/import-from-esm/index.js:100:17)
    at async start (file:///...project.../.yarn/cache/vite-bundle-visualizer-npm-1.0.0-aad67201df-9113c78bf4.zip/node_modules/vite-bundle-visualizer/index.js:25:21)
    at async file:///...project.../.yarn/cache/vite-bundle-visualizer-npm-1.0.0-aad67201df-9113c78bf4.zip/node_modules/vite-bundle-visualizer/bin.js:35:1 {
  code: 'MODULE_NOT_FOUND'
}

Node.js v20.11.0
```

### PR DESCRIPTION
**Pull request by nix6839**
Temporary fix #15

## List
- Fix cannot import vite in Yarn PnP 
- Set the node engines range to include versions that `import.meta.resolve()` is unflagged.
- Add tests for Vite3, Vite4 and yarn-pnp
- Add github action for test

## Details
```js
async function importVite() {
  /** @type {import('vite')} */
  let vite = await importFrom.silent(process.cwd(), 'vite');
  try {
    vite ??= await import(import.meta.resolve('vite'));
  } catch {}
  return vite;
}
```

In other than Yarn PnP, the `importFrom.silet()` successfully makes an assignment and then skips the next assignment. Yarn PnP seems to fail on the first assignment but works on the second dynamic import. I'll need to test it after the release and yarn dlx `vite-bundle-visualizer`, but for now, it seems to properly import vite from the executed project when run through yarn in PnP mode. (I have no idea why).

There are precaution to note:
- To run vite-bundle-visualizer in a Yarn PnP project, it must be executed only through the project's yarn commands. Examples include:
	- `yarn dlx vite-bundle-visualizer` in project
	- `yarn add -D vite-bundle-visualizer && yarn vite-bundle-visualizer` in project
	- ...

### CODE REVIEW

**Comment by KusStar** [comment]
LGTM, nice work!
